/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as TacticsRouteImport } from './routes/tactics'
import { Route as LeagueRouteImport } from './routes/league'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as CompeteRouteImport } from './routes/compete'
import { Route as IndexRouteImport } from './routes/index'

const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const TacticsRoute = TacticsRouteImport.update({
  id: '/tactics',
  path: '/tactics',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRoute = LeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const CompeteRoute = CompeteRouteImport.update({
  id: '/compete',
  path: '/compete',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compete': typeof CompeteRoute
  '/draft': typeof DraftRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/league': typeof LeagueRoute
  '/tactics': typeof TacticsRoute
  '/tournament': typeof TournamentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compete': typeof CompeteRoute
  '/draft': typeof DraftRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/league': typeof LeagueRoute
  '/tactics': typeof TacticsRoute
  '/tournament': typeof TournamentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compete': typeof CompeteRoute
  '/draft': typeof DraftRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/league': typeof LeagueRoute
  '/tactics': typeof TacticsRoute
  '/tournament': typeof TournamentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compete'
    | '/draft'
    | '/history'
    | '/home'
    | '/league'
    | '/tactics'
    | '/tournament'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compete'
    | '/draft'
    | '/history'
    | '/home'
    | '/league'
    | '/tactics'
    | '/tournament'
  id:
    | '__root__'
    | '/'
    | '/compete'
    | '/draft'
    | '/history'
    | '/home'
    | '/league'
    | '/tactics'
    | '/tournament'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompeteRoute: typeof CompeteRoute
  DraftRoute: typeof DraftRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LeagueRoute: typeof LeagueRoute
  TacticsRoute: typeof TacticsRoute
  TournamentRoute: typeof TournamentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tactics': {
      id: '/tactics'
      path: '/tactics'
      fullPath: '/tactics'
      preLoaderRoute: typeof TacticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compete': {
      id: '/compete'
      path: '/compete'
      fullPath: '/compete'
      preLoaderRoute: typeof CompeteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompeteRoute: CompeteRoute,
  DraftRoute: DraftRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LeagueRoute: LeagueRoute,
  TacticsRoute: TacticsRoute,
  TournamentRoute: TournamentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
